"""add schema_version to reports

Revision ID: 461ffae8d2f6
Revises: 931c2b80fa55
Create Date: 2026-06-22 22:27:48.630206
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '461ffae8d2f6'
down_revision: str | None = '931c2b80fa55'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('schema_version', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'schema_version')
    # ### end Alembic commands ###
