"""Add report status fields

Revision ID: 931c2b80fa55
Revises: 8dcd4fc7679f
Create Date: 2026-06-22 21:38:48.119309
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '931c2b80fa55'
down_revision: str | None = '8dcd4fc7679f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False))
    op.add_column('reports', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('task_id', sa.String(length=255), nullable=True))
    op.alter_column('reports', 'report_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('reports', 'industry',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('reports', 'market_potential',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('reports', 'recommendation',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'recommendation',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('reports', 'market_potential',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('reports', 'industry',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('reports', 'report_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('reports', 'task_id')
    op.drop_column('reports', 'error_message')
    op.drop_column('reports', 'status')
    # ### end Alembic commands ###
